login: &login
  adapter: mysql2
  username: root
  password:
  host: localhost
  reconnect: true
  local_infile: true
  pool: 5
  timeout: 5000

development:
  <<: *login
  database: nsrx_development

test:
  <<: *login
  database: nsrx_test

staging:
  <<: *login
  
production:
  <<: *login
  
